excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://blog.mmcfarland.net
title: Matt McFarland
email: contact@mattmcfarland.com
author: Matt McFarland
description: Articles created by Matt McFarland
paginate: 3
google_analytics: UA-17944087-4
